### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by dswistowski**
- add tooling
 - add tests
 - refactor `get_window`
 - delete `is_not_in_table`

There are more detailed messages in commit comments
If you have any questions, just add comments to this pull request. It will be easier to do it that way

### CODE REVIEW

**Comment by dswistowski** [comment]
I can continue, but I do not want to throw to much in one go on you

**Comment by Gmanicus** [comment]
Oh boy. If you wish, that should be alright. I should be able to get to testing this on my Windows machine on the weekend.

**Comment by dswistowski** [comment]
closing, nobody cares. will leave the branch

**Comment by Gmanicus** [comment]
@dswistowski Hey Damian! I know it has been a while, but I wanted to apologize. I'm sorry for never coming back to this and pushing it into the main branch, or otherwise using the code you contributed to the project. I've matured a bit and thought it would be better to apologize late rather than never.

Thanks again for the contribution! At this point, it's much too late to push to the main branch, but I will take time to learn from what you wrote, so rest assured that it will not be in vain :)

**Comment by dswistowski** [comment]
No worries at all

Cheers

**Pull request closed without merging**
